apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: profefe
spec:
  version: {{ .TagName }}
  homepage: https://github.com/profefe/kube-profefe
  shortDescription: Gather and manage pprof profiles from running pods
  description: |
    This plugin helps to manage pprof profiles via Profefe. It allows to
    collect profiles from running pods with Profefe and retrieve or inspect
    profiles stored in Profefe. For more information about Profefe, visit
    https://profefe.dev
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/profefe/kube-profefe/releases/download/{{ .TagName }}/kube-profefe_{{ .TagName }}_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-profefe
      files:
        - from: kubectl-profefe
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/profefe/kube-profefe/releases/download/{{ .TagName }}/kube-profefe_{{ .TagName }}_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-profefe
      files:
        - from: kubectl-profefe
          to: .
        - from: LICENSE
          to: .
